Repository kpagacz/wiki-on-fire, pull requests merged in 2021-10, with the labels that each got.

#25 Update README.md
  README.md
Labels: documentation

#15 feat(backend): addeda a scaffolding for the backend
  README.md
  giddy-banana/README.md
  giddy-banana/app.js
  giddy-banana/package-lock.json
  giddy-banana/package.json
Labels: backend

#19 feat(frontend): added basic frontend
  frontend/.browserslistrc
  frontend/.eslintrc.js
  frontend/.gitignore
  frontend/README.md
  frontend/babel.config.js
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/src/App.vue
  frontend/src/assets/logo.png
  frontend/src/components/WofHelloWorld.vue
  frontend/src/main.js
  frontend/vue.config.js
  vetur.config.js
Labels: frontend
