Repository kpagacz/wiki-on-fire, pull requests merged in 2021-12, with the labels that each got.

#123 47 user register implement
  frontend/src/pages/RegisterPage.vue
Labels: frontend

#131 refactor: refactored loginUser to return the user object
  frontend/src/httpLayers/login.http.js
  giddy-banana/controllers/loginController.js
Labels: frontend

#104 devops: added nginx to docker-compose
  .github/workflows/build-and-publish-devel-env.yaml
  docker-compose-environments/README.md
  docker-compose-environments/dev-nginx.conf
  docker-compose-environments/devel-nginx.Dockerfile
  docker-compose-environments/development-env.yml
  frontend/src/httpLayers/wofApi.js
  giddy-banana/package-lock.json
  giddy-banana/package.json
Labels: enhancement

#125 fix: added seed storage to the database
  giddy-banana/config/config.json
Labels: backend

#144 add: added the logout endpoint to the backend
  giddy-banana/controllers/logoutController.js
  giddy-banana/routes/index.js
  giddy-banana/routes/logoutRoute.js
  giddy-banana/services/logoutService.js
Labels: backend

#126 add: added examples of requests to WikiMedia API
  wikimedia-requests/README.md
  wikimedia-requests/exceptions.js
  wikimedia-requests/package-lock.json
  wikimedia-requests/package.json
  wikimedia-requests/requests.js
Labels: backend

#137 add: added cloudformation file for a test lambda
  amazon-architecture/TestLambda.yaml
Labels: devops

#139 64 login implement
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/WofHeader.vue
  frontend/src/components/icons.less
  frontend/src/main.js
  frontend/src/pages/LoginPage.vue
  frontend/src/router.js
  frontend/src/store.js
Labels: frontend

#149 add: hash passwords in the database
  giddy-banana/models/userModel.cjs
  giddy-banana/package-lock.json
  giddy-banana/package.json
  giddy-banana/services/loginService.js
  giddy-banana/services/usersService.js
  giddy-banana/src/Errors.js
  giddy-banana/src/hashing.js
Labels: backend

#161 add: added cloudformation yaml for the network configuration
  amazon-architecture/WoFVPC.yaml
Labels: devops

#165 UX - Register Page reaction on empty fields
  frontend/src/pages/RegisterPage.vue
Labels: bug, frontend

#162 add: refactored signing out the user from the application
  frontend/src/components/WofHeader.vue
  frontend/src/httpLayers/signout.http.js
  frontend/src/store.js
Labels: frontend

#152 add: added an endpoint to refresh the token
  giddy-banana/.eslintrc.cjs
  giddy-banana/config/config.example.js
  giddy-banana/controllers/loginController.js
  giddy-banana/controllers/refreshTokenController.js
  giddy-banana/routes/authRouter.js
  giddy-banana/routes/index.js
  giddy-banana/routes/refreshTokenRoute.js
  giddy-banana/services/loginService.js
  giddy-banana/services/refreshTokenService.js
Labels: backend

#160 add: added http layer for the account actions (get, delete, update)
  frontend/src/httpLayers/accountActions.http.js
  frontend/src/httpLayers/registration.http.js
  frontend/src/pages/RegisterPage.vue
  giddy-banana/controllers/aboutController.js
  giddy-banana/routes/index.js
  giddy-banana/seeders/20211113204622-demo-user.cjs
  giddy-banana/services/usersService.js
Labels: frontend

#156 Articles endpoint
  giddy-banana/controllers/articleController.js
  giddy-banana/models/articleModel.cjs
  giddy-banana/models/commentModel.cjs
  giddy-banana/models/index.cjs
  giddy-banana/routes/articleRoute.js
  giddy-banana/routes/index.js
  giddy-banana/routes/usersRoute.js
  giddy-banana/seeders/20211113204622-demo-user.cjs
  giddy-banana/seeders/20211115192909-demo-article.cjs
  giddy-banana/services/articleService.js
Labels: backend

#122 Wof small error component
  frontend/src/components/WofInfoBox.vue
  frontend/src/components/WofInput.vue
  frontend/src/components/WofSmallError.vue
Labels: frontend
