Repository kpagacz/wiki-on-fire, pull requests merged in 2022-01, with the labels that each got.

#183 27 article list
  frontend/src/components/WofArticleList.vue
  frontend/src/components/WofButton.vue
Labels: frontend

#176 35 user options
  frontend/src/components/WofOptionalSection.vue
  frontend/src/pages/PassRecoveryPage.vue
  frontend/src/pages/UserPage.vue
  frontend/src/router.js
Labels: frontend

#193 fix: fixed the refresh token controller
  giddy-banana/services/loginService.js
  giddy-banana/services/refreshTokenService.js
Labels: backend

#184 142 auto login
  frontend/src/App.vue
  frontend/src/httpLayers/autoLogin.http.js
  frontend/src/store.js
Labels: frontend

#194 add: improved error messages from the /api/users POST endpoint
  frontend/src/httpLayers/accountActions.http.js
  giddy-banana/controllers/usersController.js
  giddy-banana/models/userModel.cjs
  giddy-banana/services/usersService.js
Labels: frontend, backend

#207 devops: removed babel
  frontend/vetur.config.js
  giddy-banana/.babelrc
  giddy-banana/.eslintrc.cjs
  giddy-banana/.sequelizerc
  giddy-banana/migrations/20211104181759-create-user.cjs
  giddy-banana/migrations/20211115184638-create-article.cjs
  giddy-banana/migrations/20211115190817-create-like-it.cjs
  giddy-banana/migrations/20211118202125-create-recommend.cjs
  giddy-banana/migrations/20211118203659-create-favourite.cjs
  giddy-banana/migrations/20211121213351-create-comment.cjs
  giddy-banana/models/articleModel.cjs
  giddy-banana/models/commentModel.cjs
  giddy-banana/models/userModel.cjs
  giddy-banana/package-lock.json
  giddy-banana/package.json
  giddy-banana/seeders/20211115192909-demo-article.cjs
  giddy-banana/seeders/20211202173349-demo-like_it.cjs
  giddy-banana/seeders/20211202181113-demo-recommend.cjs
  giddy-banana/seeders/20211202181629-demo-comment.cjs
  giddy-banana/seeders/20211202182151-demo-favourite.cjs
Labels: backend, devops

#208 205 improve error
  frontend/src/pages/RegisterPage.vue
Labels: frontend

#212 174 page nav
  frontend/src/components/WofPageNav.vue
  frontend/src/components/icons.less
  frontend/src/httpLayers/autoLogin.http.js
  frontend/src/store.js
Labels: frontend

#210 feat: added backend documentation
  .github/workflows/build-and-publish-devel-env.yaml
  .github/workflows/build-deploy-docs.yaml
  .gitignore
  amazon-architecture/docsBucket.yaml
  giddy-banana/.eslintignore
  giddy-banana/.prettierignore
  giddy-banana/.prettierrc
  giddy-banana/README.md
  giddy-banana/app.js
  giddy-banana/controllers/aboutController.js
  giddy-banana/controllers/articleController.js
  giddy-banana/controllers/loginController.js
  giddy-banana/controllers/logoutController.js
  giddy-banana/controllers/refreshTokenController.js
  giddy-banana/controllers/usersController.js
  giddy-banana/jsdoc.config.json
  giddy-banana/middleware/allowedRequests.js
  giddy-banana/middleware/index.js
  giddy-banana/models/articleModel.cjs
  giddy-banana/models/articletopeditionsModel.cjs
  giddy-banana/models/articletopviewsModel.cjs
  giddy-banana/models/commentModel.cjs
  giddy-banana/models/index.cjs
  giddy-banana/models/userModel.cjs
  giddy-banana/package-lock.json
  giddy-banana/package.json
  giddy-banana/routes/articleRoute.js
  giddy-banana/routes/authRouter.js
  giddy-banana/routes/index.js
  giddy-banana/routes/loginRoute.js
  giddy-banana/routes/logoutRoute.js
  giddy-banana/routes/refreshTokenRoute.js
  giddy-banana/routes/usersRoute.js
  giddy-banana/seeders/20211113204622-demo-user.cjs
  giddy-banana/seeders/20211115192909-demo-article.cjs
  giddy-banana/seeders/20211202173349-demo-like_it.cjs
  giddy-banana/seeders/20211202181113-demo-recommend.cjs
  giddy-banana/seeders/20211202181629-demo-comment.cjs
  giddy-banana/seeders/20211202182151-demo-favourite.cjs
  giddy-banana/seeders/20220102102245-demo-articletopeditions.cjs
  giddy-banana/seeders/20220102102256-demo-articletopviews.cjs
  giddy-banana/services/articleService.js
  giddy-banana/services/loginService.js
  giddy-banana/services/logoutService.js
  giddy-banana/services/refreshTokenService.js
  giddy-banana/services/serviceErrors.js
  giddy-banana/services/usersService.js
  giddy-banana/src/Errors.js
  giddy-banana/src/hashing.js
Labels: documentation, backend, devops

#214 Fix jsdoc workflow
  .github/workflows/build-deploy-docs.yaml
Labels: devops

#182 add: added dynamo db to aws
  .github/workflows/seed-dynamo.yaml
  amazon-architecture/DynamoDB.yaml
  wikimedia-requests/package-lock.json
  wikimedia-requests/package.json
  wikimedia-requests/requests.js
  wikimedia-requests/seedMostViewedArticlesTable.js
Labels: backend, devops

#188 devops: added the AWS lambda to download data from wikimedia
  .github/workflows/build-and-publish-devel-env.yaml
  .github/workflows/deploy-wikimedia-lambda.yaml
  amazon-architecture/lambdas/download-wikimedia-data/README.md
  amazon-architecture/lambdas/download-wikimedia-data/exceptions.js
  amazon-architecture/lambdas/download-wikimedia-data/index.js
  amazon-architecture/lambdas/download-wikimedia-data/package-lock.json
  amazon-architecture/lambdas/download-wikimedia-data/package.json
  amazon-architecture/lambdas/download-wikimedia-data/requests.js
  amazon-architecture/lambdas/download-wikimedia-data/seedMostViewedArticlesTable.js
  amazon-architecture/wikimediaLambda.yaml
  wikimedia-requests/package-lock.json
Labels: backend, devops

#221 add: backend endpoint for the most viewed articles and the http layer
  frontend/src/httpLayers/mostViewedArticles.http.js
  giddy-banana/controllers/articleController.js
  giddy-banana/models/articleTopViewsModel.cjs
  giddy-banana/package-lock.json
  giddy-banana/package.json
  giddy-banana/routes/articleRoute.js
  giddy-banana/seeders/20211115192909-demo-article.cjs
  giddy-banana/services/articleService.js
Labels: frontend, backend

#225 [200_Front_Readme]
  frontend/README.md
Labels: documentation, frontend

#224 Update README.md
  README.md
Labels: documentation

#223 Create README.md
  .github/workflows/README.md
Labels: documentation, devops

#227 Update README.md
  README.md
Labels: documentation

#226 docs: expanded the backend documentation
  giddy-banana/README.md
Labels: documentation, backend

#228 docs: expanded docker-compose-environments documentation
  docker-compose-environments/README.md
Labels: documentation, devops

#229 Update README.md
  giddy-banana/README.md
Labels: documentation, backend

#231 Update seed-dynamo.yaml
  .github/workflows/seed-dynamo.yaml
Labels: bug, devops

#217 add: added a lambda to process and update the amazon rds database with new items from the dynamo table
  .github/workflows/deploy-processing-lambda.yaml
  .github/workflows/update-process-viewed-lambda.yaml
  .gitignore
  amazon-architecture/LambdaRoles.yaml
  amazon-architecture/ProcessViewedLambda.yaml
  amazon-architecture/WoFVPC.yaml
  amazon-architecture/lambdas/process-dynamo-views/index.js
  amazon-architecture/lambdas/process-dynamo-views/package-lock.json
  amazon-architecture/lambdas/process-dynamo-views/package.json
  amazon-architecture/wofApplication.yaml
  giddy-banana/.sequelizerc
  giddy-banana/README.md
  giddy-banana/config/config.cjs
  giddy-banana/controllers/aboutController.js
  giddy-banana/models/index.cjs
  wikimedia-requests/package-lock.json
Labels: backend, devops

#233 [fix_edit_email]
  frontend/src/pages/UserPage.vue
Labels: frontend

#235 docs: added readme for amazon-architecture
  amazon-architecture/README.md
Labels: documentation, devops

#220 add: cloudformation yaml for amazon rds instance
  .gitignore
  amazon-architecture/README.md
  amazon-architecture/dynamoDb.yaml
  amazon-architecture/lambdaRoles.yaml
  amazon-architecture/processViewedLambda.yaml
  amazon-architecture/wofVpc.yaml
Labels: backend, devops
